version: 1.0.{build}
image: Visual Studio 2019

environment:
  access_token:
    secure: e38088fffe1d8e387c8c2201928b4b8a424f406f

install:
- cmd: >-
    npm install -g vuepress

    yarn add -D @vuepress/plugin-google-analytics
    
build_script:
  - cmd: vuepress build
   
for:   
-
  branches:
    only:
    - master
  
  configuration: Release
  deploy_script:
    - ps: >-
        git config --global credential.helper store
        
        Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
        
    - cmd: >-
        mkdir C:\projects\dist\
        
        git clone -q --branch=gh-pages https://github.com/MuhammadAdeelUsman/expressdb.git C:\projects\dist\
        
        cd C:\projects\dist\
        
        git rm * -r -q
        
        xcopy "C:\projects\expressdb\.vuepress\dist" "C:\projects\dist" /s
        
        git config --global user.email "iq.adeel@gmail.com" 
        
        git config --global user.name "MuhammadAdeelUsman"
        
        git add .
        
        git commit -a -m "deploy github pages" -q
        
        git push origin gh-pages -f
    
-
  branches: 
   except:
     - master

  configuration: Test
